spring:
  application:
    name: internet-connectivity-tracker

ict:
  probe:
    interval-ms: 1000       # 1 second default
  elasticsearch:
    host: localhost
    port: 9200
    index: probe-results
